package argus.langdetect;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This is {@link LanguageDetectorMessages} class generated by Eclipse automatically.
 *
 * @author Nakatani Shuyo
 */
class LanguageDetectorMessages {
    private static final String BUNDLE_NAME = "messages"; //$NON-NLS-1$

    private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

    private LanguageDetectorMessages() {
    }

    public static String getString(String key) {
        try {
            return RESOURCE_BUNDLE.getString(key);
        } catch (MissingResourceException e) {
            return '!' + key + '!';
        }
    }
}
